const USUniversityList = {
  44: [
    "Amherst College",
    "Brown University",
    "Cal Tech",
    "Columbia",
    "Dartmouth",
    "Harvard",
    "MIT",
    "Pomona College",
    "Princeton",
    "Stanford",
    "Swarthmore College",
    "UC Berkeley",
    "University of Chicago",
    "University of Pennsylvania",
    "Williams College",
    "Yale",
    "a university",
  ],
  43: [
    "Duke University",
    "Georgia Institute of Technology",
    "Johns Hopkins University",
    "Rice University",
    "UCLA",
    "University of Michigan Ann Arbor",
  ],
  40: [
    "Boston University",
    "Northwestern University",
    "Tufts University",
    "University of Notre Dame",
    "University of Southern California",
    "Vanderbilt University",
  ],
  37: [
    "Emory University",
    "NYU",
    "Purdue University West Lafayette",
    "UC San Diego",
    "University of Illinois Urbana Champaign",
    "University of Wisconsin Madison",
    "Washington University in St. Louis",
  ],
  34: [
    "Georgetown University",
    "Syracuse University",
    "UC Davis",
    "UC Irvine",
    "UC Merced",
    "UC Riverside",
    "UC Santa Barbara",
    "UC Santa Cruz",
  ],
  33: [
    "Brandeis University",
    "Colorado State University",
    "DePaul University",
    "Eastern Michigan University",
    "Florida A&M University",
    "Florida State University",
    "Gonzaga University",
    "Howard University",
    "Iowa State University",
    "Kansas State University",
    "Miami University",
    "Michigan State University",
    "Oregon State University",
    "Oregon University",
    "Penn State University",
    "St. John's University",
    "Texas A&M University",
    "Texas State University",
    "Tulane University",
    "University of Alabama",
    "University of Houston",
    "University of Illinois Chicago",
    "University of Kentucky",
    "University of Maine",
    "University of Maryland",
    "University of Utah",
    "University of Virginia",
  ],
  0: [],
};

const UKUniversityList = {
  44: ["Cambridge", "Oxford"],
  43: ["Imperial College London", "UCL"],
  40: [
    "King's College",
    "London School of Economics",
    "The University of Edinburgh",
  ],
  37: [
    "University of Aston",
    "University of Bristol",
    "University of Exeter",
    "University of Lancaster",
    "University of Leeds",
    "University of York",
  ],
  34: [
    "Loughborough University",
    "University of Glasgow",
    "University of Manchester",
    "University of St Andrews",
    "University of Strathclyde",
    "University of Warwick",
    "Queenmary University",
    "University of Nottingham",
    "The University of Sheffield",
    "Newcastle University",
    "Cardiff University",
    "University of Reading",
    "University of Liverpool",
    "University of Sussex",
  ],
  33: [
    "Durham University",
    "Univeristy of Surrey",
    "University of Aberdeen",
    "University of Bath",
    "University of Birmingham",
    "University of Southampton",
    "University of West London",
    "University of Leicester",
    "City, University of London",
  ],
  0: [],
};

const SingaporeUniversityList = {
  44: ["NUS"],
  43: [],
  40: ["Nanyang Technological University"],
  37: ["SUTD"],
  34: ["Singapore Management University"],
  33: [],
  0: [],
};

const KoreaUniversityList = {
  44: ["KAIST", "Seoul National University"],
  43: ["Korea University", "Yonsei University", "POSTECH"],
  40: [
    "Hanyang University",
    "Sogang University",
    "SungKyunKwan University",
    "Ulsan National Institute of Science and Technology",
    "Daegu Gyeongbuk Institute of Science and Technology",
    "Gwangju Institute of Science and Technology",
  ],
  37: [
    "Chungang University",
    "Ewha Womens University",
    "Konkuk University",
    "Yonsei University Underwood",
    "Hankuk University of Foreign Studies",
    "Kyungpook National University",
    "Pusan National University",
    "Ajou University",
    "Dongguk University",
    "Inha University",
  ],
  34: [
    "Sookmyung University",
    "Sungshin University",
    "Jeonbuk National University",
    "University of Ulsan",
    "The Catholic University of Korea",
    "Kyung Hee University",
    "Sejong University",
  ],
  33: [],
  0: [],
};

const CanadaUniversityList = {
  44: [],
  43: [],
  40: [],
  37: [
    "McGill University",
    "University of British Columbia",
    "University of Toronto",
    "University of Waterloo",
  ],
  34: ["University of Alberta"],
  33: [
    "McMaster University",
    "Universite de Montreal",
    "University of Calgary",
    "University of Ottawa",
    "Western University",
    "Dalhousie University",
    "Simon Fraser University",
    "University of Victoria",
    "University of Manitoba",
    "Laval University",
    "York University",
  ],
  0: [],
};

const HKUniversityList = {
  44: [],
  43: [],
  40: [],
  37: [
    "Chinese University of Hongkong",
    "Hong Kong University",
    "Hong Kong University of Science and Technology",
  ],
  34: ["Hong Kong Polytechnic University"],
  33: [
    "City University of Hong Kong",
    "Hong Kong Baptist University",
    "Lingnan University, Hong Kong",
  ],
  0: [],
};

const AustraliaUniversityList = {
  44: [],
  43: ["University of Melbourne"],
  40: [],
  37: ["Australian National University"],
  34: ["University of Sydney", "University of New South Wales Sydney"],
  33: ["University of Queensland", "Monash University"],
  0: [],
};

const JapanUniversityList = {
  44: [],
  43: [],
  40: [],
  37: ["University of Tokyo", "Waseda University"],
  34: [],
  33: [
    "Kyoto University",
    "Osaka University",
    "Tohoku University",
    "Nagoya University",
    "Hokkaido University",
    "Keio University",
  ],
  0: [],
};

const USUniversityInfo = {
  MIT: {
    name: "Massachusetts Institute of Technology",
    IBScore: "44-45",
    tuition: "$59,750",
    rank: 1,
    img: "/img/univ_logos/MIT.png",
  },
  Harvard: {
    name: "Harvard University",
    IBScore: "44-45",
    tuition: "$54,269",
    rank: 4,
    img: "/img/univ_logos/Harvard.png",
  },
  Stanford: {
    name: "Stanford University",
    IBScore: "44-45",
    tuition: "$41,154",
    rank: 5,
    img: "/img/univ_logos/Stanford_University.png",
  },
  "UC Berkeley": {
    name: "University of California, Berkeley",
    IBScore: "44-45",
    tuition: "$15,602",
    rank: 10,
    img: "/img/univ_logos/UC_Berkeley.png",
  },
  Yale: {
    name: "Yale University",
    IBScore: "44-45",
    tuition: "$64,700",
    rank: 16,
    img: "/img/univ_logos/Yale.png",
  },
  Princeton: {
    name: "Princeton University",
    IBScore: "44-45",
    tuition: "$59,710",
    rank: 17,
    img: "/img/univ_logos/University-of-Princeton.png",
  },
  Columbia: {
    name: "Columbia University",
    IBScore: "44-45",
    tuition: "$65,524",
    rank: 23,
    img: "/img/univ_logos/Columbia University.png",
  },
  Dartmouth: {
    name: "Dartmouth College",
    IBScore: "44-45",
    tuition: "$63,684",
    rank: 237,
    img: "/img/univ_logos/Dartmouth.png",
  },
  "University of Pennsylvania": {
    name: "University of Pennsylvania",
    IBScore: "44-45",
    tuition: "$58,620",
    rank: 12,
    img: "/img/univ_logos/UPenn.png",
  },
  "Brown University": {
    name: "Brown University",
    IBScore: "44-45",
    tuition: "$65,656",
    rank: 73,
    img: "/img/univ_logos/Brown.png",
  },
  "Cal Tech": {
    name: "California Institute of Technology",
    IBScore: "44-45",
    tuition: "$60,816",
    rank: 15,
    img: "/img/univ_logos/Caltech.png",
  },
  "University of Chicago": {
    name: "University of Chicago",
    IBScore: "44-45",
    tuition: "$63,801",
    rank: 11,
    img: "/img/univ_logos/The university of Chicago.png",
  },
  "Williams College": {
    name: "Williams College",
    IBScore: "44-45",
    tuition: "$64,540",
    rank: "301-330",
    img: "/img/univ_logos/Williams College.png",
  },
  "Amherst College": {
    name: "Amherst College",
    IBScore: "44-45",
    tuition: "$33,325",
    rank: "201-250",
    img: "/img/univ_logos/amherst college.png",
  },
  "Pomona College": {
    name: "Pomona College",
    IBScore: "44-45",
    tuition: "$61,906",
    rank: 959,
    img: "/img/univ_logos/pomona.png",
  },
  "Swarthmore College": {
    name: "Swarthmore College",
    IBScore: "44-45",
    tuition: "$61,992",
    rank: 741,
    img: "/img/univ_logos/swarthmore.png",
  },
  "Duke University": {
    name: "Duke University",
    IBScore: "43",
    tuition: "$63,450",
    rank: 57,
    img: "/img/univ_logos/Duke_University.png",
  },
  "Georgia Institute of Technology": {
    name: "Georgia Institute of Technology",
    IBScore: "43",
    tuition: "$12,852",
    rank: 97,
    img: "/img/univ_logos/Georgia Institute of Technology.png",
  },
  "Johns Hopkins University": {
    name: "Johns Hopkins University",
    IBScore: "43",
    tuition: "$62,840",
    rank: 28,
    img: "/img/univ_logos/Johns Hopkins university.png",
  },
  "Rice University": {
    name: "Rice University",
    IBScore: "43",
    tuition: "$57,210",
    rank: 145,
    img: "/img/univ_logos/rice university.png",
  },
  UCLA: {
    name: "University of California, Los Angeles",
    IBScore: "43",
    tuition: "$14,478",
    rank: 29,
    img: "/img/univ_logos/UCLA.png",
  },
  "University of Michigan Ann Arbor": {
    name: "University of Michigan Ann Arbor",
    IBScore: "43",
    tuition: "$50,800",
    rank: 33,
    img: "/img/univ_logos/University_of_Michigan.png",
  },
  "Boston University": {
    name: "Boston University",
    IBScore: "40-42",
    tuition: "$63,798",
    rank: 93,
    img: "/img/univ_logos/Boston.png",
  },
  "Northwestern University": {
    name: "Northwestern University",
    IBScore: "40-42",
    tuition: "$62,391",
    rank: 47,
    img: "/img/univ_logos/Northwestern_University.png",
  },
  "Tufts University": {
    name: "Tufts University",
    IBScore: "40-42",
    tuition: "$67,844",
    rank: 379,
    img: "/img/univ_logos/tufts-university.png",
  },
  "University of Notre Dame": {
    name: "University of Notre Dame",
    IBScore: "40-42",
    tuition: "$62,693",
    rank: 304,
    img: "/img/univ_logos/Notre_Dame.png",
  },
  "University of Southern California": {
    name: "University of Southern California",
    IBScore: "40-42",
    tuition: "$66,640",
    rank: 116,
    img: "/img/univ_logos/University_of_Southern_California.png",
  },
  "Vanderbilt University": {
    name: "Vanderbilt University",
    IBScore: "40-42",
    tuition: "$58,130",
    rank: 261,
    img: "/img/univ_logos/Vanderbilt_University.png",
  },
  "Emory University": {
    name: "Emory University",
    IBScore: "37-39",
    tuition: "$59,920",
    rank: 166,
    img: "/img/univ_logos/Emory_University.png",
  },
  NYU: {
    name: "New York University",
    IBScore: "37-39",
    tuition: "$60,438",
    rank: 38,
    img: "/img/univ_logos/NYU.png",
  },
  "Purdue University West Lafayette": {
    name: "Purdue University West Lafayette",
    IBScore: "37-39",
    tuition: "$31,104",
    rank: 99,
    img: "/img/univ_logos/Purdue_University.png",
  },
  "UC San Diego": {
    name: "University of California, San Diego",
    IBScore: "37-39",
    tuition: "$18,480",
    rank: 62,
    img: "/img/univ_logos/UCSD.png",
  },
  "University of Illinois Urbana Champaign": {
    name: "University of Illinois Urbana Champaign",
    IBScore: "37-39",
    tuition: "$43,894",
    rank: 64,
    img: "/img/univ_logos/Illinois.png",
  },
  "University of Wisconsin Madison": {
    name: "University of Wisconsin Madison",
    IBScore: "37-39",
    tuition: "$40,612",
    rank: 102,
    img: "/img/univ_logos/University_of_Wisconsin.png",
  },
  "Washington University in St. Louis": {
    name: "Washington University in St. Louis",
    IBScore: "37-39",
    tuition: "$61,750",
    rank: 154,
    img: "/img/univ_logos/Washington University in St_ Louis.png",
  },
  "Georgetown University": {
    name: "Georgetown University",
    IBScore: "34-36",
    tuition: "$32,448",
    rank: 297,
    img: "/img/univ_logos/Georgetown University - US.png",
  },
  "Syracuse University": {
    name: "Syracuse University",
    IBScore: "34-36",
    tuition: "$61,310",
    rank: "781-790",
    img: "/img/univ_logos/Syracuse University.png",
  },
  "UC Davis": {
    name: "University of California, Davis",
    IBScore: "34-36",
    tuition: "$44,130",
    rank: 118,
    img: "/img/univ_logos/uc-davis.png",
  },
  "UC Irvine": {
    name: "University of California, Irvine",
    IBScore: "34-36",
    tuition: "$34,124",
    rank: 268,
    img: "/img/univ_logos/university-of-california-irvine.png",
  },
  "UC Merced": {
    name: "University of California, Merced",
    IBScore: "34-36",
    tuition: "$43,777",
    rank: 301,
    img: "/img/univ_logos/UC Merced - US.png",
  },
  "UC Riverside": {
    name: "University of California, Riverside",
    IBScore: "34-36",
    tuition: "$46,326",
    rank: 404,
    img: "/img/univ_logos/UC Riverside - US.png",
  },
  "UC Santa Barbara": {
    name: "University of California, Santa Barbara",
    IBScore: "34-36",
    tuition: "$14,391",
    rank: 163,
    img: "/img/univ_logos/UCSB.png",
  },
  "UC Santa Cruz": {
    name: "University of California, Santa Cruz",
    IBScore: "34-36",
    tuition: "$47,862",
    rank: 332,
    img: "/img/univ_logos/UC Santa Cruz - US.png",
  },
  "Brandeis University": {
    name: "Brandeis University",
    IBScore: "≤ 34",
    tuition: "$64,348",
    rank: "661-670",
    img: "/img/univ_logos/Brandeis University.png",
  },
  "Colorado State University": {
    name: "Colorado State University",
    IBScore: "≤ 34",
    tuition: "$33,752",
    rank: 409,
    img: "/img/univ_logos/Colorado State University.png",
  },
  "DePaul University": {
    name: "DePaul University",
    IBScore: "≤ 34",
    tuition: "$43,665",
    rank: 151,
    img: "/img/univ_logos/DePaul University.png",
  },
  "Eastern Michigan University": {
    name: "Eastern Michigan University",
    IBScore: "≤ 34",
    tuition: "$15,510",
    rank: "299-440",
    img: "/img/univ_logos/Eastern Michigan University.png",
  },
  "Florida A&M University": {
    name: "Florida A&M University",
    IBScore: "≤ 34",
    tuition: "$17,725",
    rank: "1201-1400",
    img: "/img/univ_logos/Florida A&M University.png",
  },
  "Florida State University": {
    name: "Florida State University",
    IBScore: "≤ 34",
    tuition: "$18,746",
    rank: 461,
    img: "/img/univ_logos/Florida State University.png",
  },
  "Gonzaga University": {
    name: "Gonzaga University",
    IBScore: "≤ 34",
    tuition: "$52,540",
    rank: 93,
    img: "/img/univ_logos/Gonzaga University.png",
  },
  "Howard University": {
    name: "Howard University",
    IBScore: "≤ 34",
    tuition: "$33,344",
    rank: "1001-1200",
    img: "/img/univ_logos/Howard University.png",
  },
  "Iowa State University": {
    name: "Iowa State University",
    IBScore: "≤ 34",
    tuition: "$14,004",
    rank: 400,
    img: "/img/univ_logos/Iowa State University.png",
  },
  "Kansas State University": {
    name: "Kansas State University",
    IBScore: "≤ 34",
    tuition: "$27,816",
    rank: "851-900",
    img: "/img/univ_logos/Kansas State University.png",
  },
  "Miami University": {
    name: "Miami University",
    IBScore: "≤ 34",
    tuition: "$14,628",
    rank: "1201-1400",
    img: "/img/univ_logos/Miami University.png",
  },
  "Michigan State University": {
    name: "Michigan State University",
    IBScore: "≤ 34",
    tuition: "$43,435",
    rank: 136,
    img: "/img/univ_logos/Michigan State University.png",
  },
  "Oregon State University": {
    name: "Oregon State University",
    IBScore: "≤ 34",
    tuition: "$36,567",
    rank: 505,
    img: "/img/univ_logos/Oregon State University.png",
  },
  "Oregon University": {
    name: "Oregon University",
    IBScore: "≤ 34",
    tuition: "$43,302",
    rank: "701-750",
    img: "/img/univ_logos/Oregon University.png",
  },
  "Penn State University": {
    name: "Penn State University",
    IBScore: "≤ 34",
    tuition: "$41,126",
    rank: 83,
    img: "/img/univ_logos/Penn State University.png",
  },
  "St. John's University": {
    name: "St. John's University",
    IBScore: "≤ 34",
    tuition: "$48,500",
    rank: "401-500",
    img: "/img/univ_logos/St. John's University.png",
  },
  "Texas A&M University": {
    name: "Texas A&M University",
    IBScore: "≤ 34",
    tuition: "$39,796",
    rank: 134,
    img: "/img/univ_logos/Texas A&M University.png",
  },
  "Texas State University": {
    name: "Texas State University",
    IBScore: "≤ 34",
    tuition: "$24,280",
    rank: "201-250",
    img: "/img/univ_logos/Texas State University.png",
  },
  "Tulane University": {
    name: "Tulane University",
    IBScore: "≤ 34",
    tuition: "$65,538",
    rank: "551-600",
    img: "/img/univ_logos/Tulane University .png",
  },
  "University of Alabama": {
    name: "University of Alabama",
    IBScore: "≤ 34",
    tuition: "$32,400",
    rank: "951-1000",
    img: "/img/univ_logos/University of Alabama.png",
  },
  "University of Houston": {
    name: "University of Houston",
    IBScore: "≤ 34",
    tuition: "$27,110",
    rank: "641-650",
    img: "/img/univ_logos/University of Houston.png",
  },
  "University of Illinois Chicago": {
    name: "University of Illinois Chicago",
    IBScore: "≤ 34",
    tuition: "$32,833",
    rank: 323,
    img: "/img/univ_logos/University of Illinois Chicago.png",
  },
  "University of Kentucky": {
    name: "University of Kentucky",
    IBScore: "≤ 34",
    tuition: "$33,406",
    rank: "681-690",
    img: "/img/univ_logos/University of Kentucky.png",
  },
  "University of Maine": {
    name: "University of Maine",
    IBScore: "≤ 34",
    tuition: "$30,030",
    rank: "201-250",
    img: "/img/univ_logos/University of Maine.png",
  },
  "University of Maryland": {
    name: "University of Maryland",
    IBScore: "≤ 34",
    tuition: "$40,306",
    rank: 169,
    img: "/img/univ_logos/University of Maryland.png",
  },
  "University of Utah": {
    name: "University of Utah",
    IBScore: "≤ 34",
    tuition: "$31,104",
    rank: 441,
    img: "/img/univ_logos/University of Utah.png",
  },
  "University of Virginia": {
    name: "University of Virginia",
    IBScore: "≤ 34",
    tuition: "$58,950",
    rank: 260,
    img: "/img/univ_logos/University_of_Virginia.png",
  },
};

const UKUniversityInfo = {
  Cambridge: {
    name: "University of Cambridge",
    IBScore: "44-45",
    tuition: "£39,162",
    rank: 2,
    img: "/img/univ_logos/University of Cambridge.png",
  },
  Oxford: {
    name: "University of Oxford",
    IBScore: "44-45",
    tuition: "£48,620",
    rank: 3,
    img: "/img/univ_logos/University of Oxford.png",
  },
  "Imperial College London": {
    name: "Imperial College London",
    IBScore: "43",
    tuition: "£36,700",
    rank: 6,
    img: "/img/univ_logos/Imperial College London.png",
  },
  UCL: {
    name: "University College London",
    IBScore: "43",
    tuition: "£28,610",
    rank: 9,
    img: "/img/univ_logos/University College London (UCL).png",
  },
  "King's College": {
    name: "King's College",
    IBScore: "40-42",
    tuition: "£22,500",
    rank: 40,
    img: "/img/univ_logos/King's College.png",
  },
  "London School of Economics": {
    name: "London School of Economics",
    IBScore: "40-42",
    tuition: "£25,272",
    rank: 45,
    img: "/img/univ_logos/LSE London School of Economics and Political Science.png",
  },
  "The University of Edinburgh": {
    name: "The University of Edinburgh",
    IBScore: "40-42",
    tuition: "£21,715",
    rank: 22,
    img: "/img/univ_logos/University of Edinburgh.png",
  },
  "University of Aston": {
    name: "University of Aston",
    IBScore: "37-39",
    tuition: "£24,500",
    rank: 446,
    img: "/img/univ_logos/University of Aston.png",
  },
  "University of Bristol": {
    name: "University of Bristol",
    IBScore: "37-39",
    tuition: "£15,750",
    rank: 55,
    img: "/img/univ_logos/University of Bristol.png",
  },
  "University of Exeter": {
    name: "University of Exeter",
    IBScore: "37-39",
    tuition: "£23,700",
    rank: 153,
    img: "/img/univ_logos/University of Exeter.png",
  },
  "University of Lancaster": {
    name: "University of Lancaster",
    IBScore: "37-39",
    tuition: "£21,200",
    rank: 122,
    img: "/img/univ_logos/Lancaster University.png",
  },
  "University of Leeds": {
    name: "University of Leeds",
    IBScore: "37-39",
    tuition: "£16,000",
    rank: 75,
    img: "/img/univ_logos/University of Leeds.png",
  },
  "University of York": {
    name: "University of York",
    IBScore: "37-39",
    tuition: "£36,722",
    rank: 167,
    img: "/img/univ_logos/University of York.png",
  },
  "Loughborough University": {
    name: "Loughborough University",
    IBScore: "34-36",
    tuition: "£28,600",
    rank: 212,
    img: "/img/univ_logos/Loughborough University.png",
  },
  "University of Glasgow": {
    name: "University of Glasgow",
    IBScore: "34-36",
    tuition: "£21,210",
    rank: 76,
    img: "/img/univ_logos/University of Glasgow.png",
  },
  "University of Manchester": {
    name: "University of Manchester",
    IBScore: "34-36",
    tuition: "£9,250",
    rank: 32,
    img: "/img/univ_logos/The University of Manchester.png",
  },
  "University of St Andrews": {
    name: "University of St Andrews",
    IBScore: "34-36",
    tuition: "£25,880",
    rank: 95,
    img: "/img/univ_logos/University of St Andrews.png",
  },
  "University of Strathclyde": {
    name: "University of Strathclyde",
    IBScore: "34-36",
    tuition: "£16,100",
    rank: 276,
    img: "/img/univ_logos/University of Strathclyde.png",
  },
  "University of Warwick": {
    name: "University of Warwick",
    IBScore: "34-36",
    tuition: "£27,060",
    rank: 67,
    img: "/img/univ_logos/University of Warwick Warw.png",
  },
  "Durham University": {
    name: "Durham University",
    IBScore: "≤ 34",
    tuition: "£20,500",
    rank: 78,
    img: "/img/univ_logos/durham-university.png",
  },
  "Univeristy of Surrey": {
    name: "Univeristy of Surrey",
    IBScore: "≤ 34",
    tuition: "£23,100",
    rank: 244,
    img: "/img/univ_logos/university-of-surrey.png",
  },
  "University of Aberdeen": {
    name: "University of Aberdeen",
    IBScore: "≤ 34",
    tuition: "£20,800",
    rank: 208,
    img: "/img/univ_logos/University of Aberdeen.png",
  },
  "University of Bath": {
    name: "University of Bath",
    IBScore: "≤ 34",
    tuition: "£25,700",
    rank: 148,
    img: "/img/univ_logos/University of Bath.png",
  },
  "University of Birmingham": {
    name: "University of Birmingham",
    IBScore: "≤ 34",
    tuition: "£24,600",
    rank: 84,
    img: "/img/univ_logos/University of Birmingham.png",
  },
  "University of Southampton": {
    name: "University of Southampton",
    IBScore: "≤ 34",
    tuition: "£22,300",
    rank: 81,
    img: "/img/univ_logos/University of Southampton.png",
  },
  "University of West London": {
    name: "University of West London",
    IBScore: "≤ 34",
    tuition: "£13,700",
    rank: "801-1000",
    img: "/img/univ_logos/University of West London.png",
  },

  "Queenmary University": {
    name: "Queenmary University",
    IBScore: "34-36",
    tuition: "£28,350",
    rank: 145,
    img: "/img/univ_logos/Queenmary University.png",
  },
  "University of Nottingham": {
    name: "University of Nottingham",
    IBScore: "34-36",
    tuition: "£30,750",
    rank: 100,
    img: "/img/univ_logos/the-university-of-nottingham.png",
  },

  "The University of Sheffield": {
    name: "The University of Sheffield",
    IBScore: "34-36",
    tuition: "£29,110",
    rank: 104,
    img: "/img/univ_logos/university-of-sheffield-new-20227008.logowik.com.webp",
  },
  "Newcastle University": {
    name: "Newcastle University",
    IBScore: "34-36",
    tuition: "£28,190",
    rank: 110,
    img: "/img/univ_logos/Newcastle-University-Logo.png",
  },
  "Cardiff University": {
    name: "Cardiff University",
    IBScore: "34-36",
    tuition: "£28,200",
    rank: 154,
    img: "/img/univ_logos/Cardiff University.png",
  },

  "University of Reading": {
    name: "University of Reading",
    IBScore: "34-36",
    tuition: "£29,950",
    rank: 169,
    img: "/img/univ_logos/university-of-reading-logo-vector.png",
  },
  "University of Liverpool": {
    name: "University of Liverpool",
    IBScore: "34-36",
    tuition: "£27,200",
    rank: 176,
    img: "/img/univ_logos/University of Liverpool.jpg",
  },
  "University of Sussex": {
    name: "University of Sussex",
    IBScore: "34-36",
    tuition: "£21,500",
    rank: 218,
    img: "/img/univ_logos/University_of_Sussex_Logo.png",
  },
  "University of Leicester": {
    name: "University of Leicester",
    IBScore: "≤ 34",
    tuition: "£24,500",
    rank: 272,
    img: "/img/univ_logos/leicester.png",
  },
  "City, University of London": {
    name: "City, University of London",
    IBScore: "≤ 34",
    tuition: "£20,700",
    rank: 328,
    img: "/img/univ_logos/City University of London.png",
  },
};

const SingaporeUniversityInfo = {
  NUS: {
    name: "National University of Singapore",
    IBScore: "44-45",
    tuition: "$20,850",
    rank: 8,
    img: "/img/univ_logos/NUS.png",
  },
  "Nanyang Technological University": {
    name: "Nanyang Technological University",
    IBScore: "40-42",
    tuition: "$38,160",
    rank: 26,
    img: "/img/univ_logos/Nanyang_Technological_University.png",
  },
  SUTD: {
    name: "Singapore University of Technology and Design",
    IBScore: "37-39",
    tuition: "$31,950",
    rank: 429,
    img: "/img/univ_logos/SUTD-Singapore-University-of-Technology-and-Design.png",
  },
  "Singapore Management University": {
    name: "Singapore Management University",
    IBScore: "34-36",
    tuition: "HKD 25,080",
    rank: 545,
    img: "/img/univ_logos/singapore-management-university-logo-png-transparent.png",
  },
};

const AustraliaUniversityInfo = {
  "University of Melbourne": {
    name: "University of Melbourne",
    IBScore: "43",
    tuition: "AUD 49,326",
    rank: 14,
    img: "/img/univ_logos/the-university-of-melbourne-logo-black-and-white.png",
  },

  "University of Sydney": {
    name: "University of Sydney",
    IBScore: "34-36",
    tuition: "AUD 52,000",
    rank: 19,
    img: "/img/univ_logos/university-of-sydney-logo-DBC20EBA62-seeklogo.com.png",
  },

  "Australian National University": {
    name: "Australian National University",
    IBScore: "37-39",
    tuition: "AUD 48,035",
    rank: 34,
    img: "/img/univ_logos/Australian National University.png",
  },

  "University of New South Wales Sydney": {
    name: "University of New South Wales Sydney",
    IBScore: "34-36",
    tuition: "AUD 42,500",
    rank: 19,
    img: "/img/univ_logos/university-of-new-south-wales-logo-png-transparent-background.png",
  },

  "University of Queensland": {
    name: "University of Queensland",
    IBScore: "≤ 34",
    tuition: "AUD 48,160",
    rank: 43,
    img: "/img/univ_logos/university-of-queensland-logo-DA3D407ABB-seeklogo.com.png",
  },

  "Monash University": {
    name: "Monash University",
    IBScore: "≤ 34",
    tuition: "AUD 52,200",
    rank: 42,
    img: "/img/univ_logos/Monash University.png",
  },
};
const KoreaUniversityInfo = {
  KAIST: {
    name: "KAIST",
    IBScore: "44-45",
    tuition: "₩9,559,000",
    rank: 56,
    img: "/img/univ_logos/kaist.png",
  },
  "Seoul National University": {
    name: "Seoul National University",
    IBScore: "44-45",
    tuition: "₩6,330,000",
    rank: 41,
    img: "/img/univ_logos/seouluniv.png",
  },
  "Korea University": {
    name: "Korea University",
    IBScore: "43",
    tuition: "₩5,000,000",
    rank: 79,
    img: "/img/univ_logos/Korea University.png",
  },
  POSTECH: {
    name: "POSTECH",
    IBScore: "43",
    tuition: "₩5,614,000",
    rank: 100,
    img: "/img/univ_logos/postech.png",
  },
  "Yonsei University": {
    name: "Yonsei University",
    IBScore: "43",
    tuition: "₩4.281,000",
    rank: 76,
    img: "/img/univ_logos/Yonsei University.png",
  },
  "Hanyang University": {
    name: "Hanyang University",
    IBScore: "40-42",
    tuition: "$9,400",
    rank: 164,
    img: "/img/univ_logos/Hanyang University.png",
  },
  "Sogang University": {
    name: "Sogang University",
    IBScore: "40-42",
    tuition: "$6,154",
    rank: 509,
    img: "/img/univ_logos/Sogang University.png",
  },
  "SungKyunKwan University": {
    name: "SungKyunKwan University",
    IBScore: "40-42",
    tuition: "$4,000",
    rank: 145,
    img: "/img/univ_logos/SungKyunKwan University.png",
  },
  "Chungang University": {
    name: "Chungang University",
    IBScore: "37-39",
    tuition: "$9,459",
    rank: 494,
    img: "/img/univ_logos/Chung-Ang_University.png",
  },
  "Ewha Womens University": {
    name: "Ewha Womens University",
    IBScore: "37-39",
    tuition: "₩4,500,000",
    rank: 498,
    img: "/img/univ_logos/Ewha Womens University.png",
  },
  "Konkuk University": {
    name: "Konkuk University",
    IBScore: "37-39",
    tuition: "￦5,643,000",
    rank: "801-850",
    img: "/img/univ_logos/Konkuk University.png",
  },
  "Hankuk University of Foreign Studies": {
    name: "Hankuk University of Foreign Studies",
    IBScore: "37-39",
    tuition: "₩7,184,000",
    rank: 575,
    img: "/img/univ_logos/hufs.jpeg",
  },
  "Yonsei University Underwood": {
    name: "Yonsei University Underwood",
    IBScore: "37-39",
    tuition: "₩7,464,000",
    rank: 76,
    img: "/img/univ_logos/Yonsei University Underwood.png",
  },
  "Sookmyung University": {
    name: "Sookmyung University",
    IBScore: "34-36",
    tuition: "￦3,550,000",
    rank: "1201-1400",
    img: "/img/univ_logos/Sookmyung University.png",
  },
  "Sungshin University": {
    name: "Sungshin University",
    IBScore: "34-36",
    tuition: "￦4,123,000",
    rank: "901-905",
    img: "/img/univ_logos/Sungshin.png",
  },

  "Ulsan National Institute of Science and Technology": {
    name: "Ulsan National Institute of Science and Technology",
    IBScore: "40-42",
    tuition: "￦6,211,000",
    rank: 266,
    img: "/img/univ_logos/UNIST.jpeg",
  },

  "Daegu Gyeongbuk Institute of Science and Technology": {
    name: "Daegu Gyeongbuk Institute of Science and Technology",
    IBScore: "40-42",
    tuition: "￦7,280,000",
    rank: 307,
    img: "/img/univ_logos/DGIST.jpeg",
  },

  "Gwangju Institute of Science and Technology": {
    name: "Gwangju Institute of Science and Technology",
    IBScore: "40-42",
    tuition: "￦2,060,000",
    rank: 328,
    img: "/img/univ_logos/GIST.jpeg",
  },
  "Kyung Hee University": {
    name: "Kyung Hee University",
    IBScore: "34-36",
    tuition: "￦7,991,000",
    rank: 332,
    img: "/img/univ_logos/경희대.jpeg",
  },

  "Sejong University": {
    name: "Sejong University",
    IBScore: "34-36",
    tuition: "￦7,945,000",
    rank: 436,
    img: "/img/univ_logos/세종대.jpeg",
  },

  "Kyungpook National University": {
    name: "Kyungpook National University",
    IBScore: "37-39",
    tuition: "￦4,500,000",
    rank: 520,
    img: "/img/univ_logos/경북대.jpeg",
  },

  "Pusan National University": {
    name: "Pusan National University",
    IBScore: "37-39",
    tuition: "￦4,465,000",
    rank: "611-620",
    img: "/img/univ_logos/부산대.jpeg",
  },
  "Ajou University": {
    name: "Ajou University",
    IBScore: "37-39",
    tuition: "￦8,312,000",
    rank: "631-640",
    img: "/img/univ_logos/아주대.jpeg",
  },
  "Dongguk University": {
    name: "Dongguk University",
    IBScore: "37-39",
    tuition: "￦8,007,000",
    rank: "671-680",
    img: "/img/univ_logos/동국대.png",
  },

  "Inha University": {
    name: "Inha University",
    IBScore: "37-39",
    tuition: "￦7,771,000",
    rank: "691-700",
    img: "/img/univ_logos/인하대.jpeg",
  },

  "Jeonbuk National University": {
    name: "Jeonbuk National University",
    IBScore: "34-36",
    tuition: "￦4,432,000",
    rank: "721-730",
    img: "/img/univ_logos/전북대.jpeg",
  },

  "University of Ulsan": {
    name: "University of Ulsan",
    IBScore: "34-36",
    tuition: "￦7,334,000",
    rank: "751-760",
    img: "/img/univ_logos/울산대.jpeg",
  },

  "The Catholic University of Korea": {
    name: "The Catholic University of Korea",
    IBScore: "34-36",
    tuition: "￦7,022,000",
    rank: "781-790",
    img: "/img/univ_logos/가톨릭대학교.jpeg",
  },
};

const CanadaUniversityInfo = {
  "McGill University": {
    name: "McGill University",
    IBScore: "37-39",
    tuition: "CAD 65,604",
    rank: 30,
    img: "/img/univ_logos/McGill_University.png",
  },
  "University of British Columbia": {
    name: "University of British Columbia",
    IBScore: "37-39",
    tuition: "CAD 61,743",
    rank: 34,
    img: "/img/univ_logos/UBC- University of British Columbia.png",
  },
  "University of Toronto": {
    name: "University of Toronto",
    IBScore: "37-39",
    tuition: "CAD 65,076",
    rank: 21,
    img: "/img/univ_logos/University_of_Toronto.png",
  },
  "University of Waterloo": {
    name: "University of Waterloo",
    IBScore: "37-39",
    tuition: "CAD 67,941",
    rank: 112,
    img: "/img/univ_logos/University Of Waterloo.png",
  },

  "University of Alberta": {
    name: "University of Alberta",
    IBScore: "34-36",
    tuition: "CAD 33,968",
    rank: 111,
    img: "/img/univ_logos/university-of-alberta-3-logo.png",
  },

  "McMaster University": {
    name: "McMaster University",
    IBScore: "≤ 34",
    tuition: "CAD 44,625",
    rank: 189,
    img: "/img/univ_logos/McMaster_University_logo.svg.png",
  },

  "Universite de Montreal": {
    name: "Universite de Montreal",
    IBScore: "≤ 34",
    tuition: "CAD 56,507",
    rank: 141,
    img: "/img/univ_logos/University of Montreal.png",
  },

  "University of Calgary": {
    name: "University of Calgary",
    IBScore: "≤ 34",
    tuition: "CAD 32,543",
    rank: 182,
    img: "/img/univ_logos/UCalgary-vertical-logo_1.png",
  },

  "University of Ottawa": {
    name: "University of Ottawa",
    IBScore: "≤ 34",
    tuition: "CAD 57,910",
    rank: 203,
    img: "/img/univ_logos/university-of-ottawa-logo-88B9787547-seeklogo.com.png",
  },

  "Western University": {
    name: "Western University",
    IBScore: "≤ 34",
    tuition: "CAD 42,233",
    rank: 114,
    img: "/img/univ_logos/western_landingr127596624961852879370484998391615659684704052568r.png",
  },

  "Dalhousie University": {
    name: "Dalhousie University",
    IBScore: "≤ 34",
    tuition: "CAD 36,030",
    rank: 298,
    img: "/img/univ_logos/Dalhousie University.png",
  },

  "Simon Fraser University": {
    name: "Simon Fraser University",
    IBScore: "≤ 34",
    tuition: "CAD 42,898",
    rank: 318,
    img: "/img/univ_logos/SFU-block-logo.svg.png",
  },

  "University of Victoria": {
    name: "University of Victoria",
    IBScore: "≤ 34",
    tuition: "CAD 32,007",
    rank: 322,
    img: "/img/univ_logos/university-of-victoria-logo-DEF809D6B0-seeklogo.com.png",
  },

  "University of Manitoba": {
    name: "University of Manitoba",
    IBScore: "≤ 34",
    tuition: "CAD 22,830",
    rank: "671-680",
    img: "/img/univ_logos/University-of-Manitoba-350x169.png",
  },

  "Laval University": {
    name: "Laval University",
    IBScore: "≤ 34",
    tuition: "CAD 40,700",
    rank: 441,
    img: "/img/univ_logos/universite-laval-logo-B83BF03158-seeklogo.com.png",
  },

  "York University": {
    name: "York University",
    IBScore: "≤ 34",
    tuition: "CAD 36,555",
    rank: 353,
    img: "/img/univ_logos/university-of-york8313.jpg",
  },
};

const JapanUniversityInfo = {
  "University of Tokyo": {
    name: "University of Tokyo",
    IBScore: "37-39",
    tuition: "¥834,800",
    rank: 28,
    img: "/img/univ_logos/University_of_Tokyo-Logo.wine.png",
  },

  "Kyoto University": {
    name: "Kyoto University",
    IBScore: "≤ 34",
    tuition: "¥834,800",
    rank: 46,
    img: "/img/univ_logos/Kyoto University.png",
  },
  "Osaka University": {
    name: "Osaka University",
    IBScore: "≤ 34",
    tuition: "¥834,800",
    rank: 80,
    img: "/img/univ_logos/Osaka_University_Logo.png",
  },
  "Tohoku University": {
    name: "Tohoku University",
    IBScore: "≤ 34",
    tuition: "¥834,800",
    rank: 113,
    img: "/img/univ_logos/Tohoku_University_Logo.svg.png",
  },

  "Nagoya University": {
    name: "Nagoya University",
    IBScore: "≤ 34",
    tuition: "¥822,800",
    rank: 176,
    img: "/img/univ_logos/Nagoya University.png",
  },
  "Hokkaido University": {
    name: "Hokkaido University",
    IBScore: "≤ 34",
    tuition: "¥834,800",
    rank: 196,
    img: "/img/univ_logos/Hokkaido University.png",
  },

  "Waseda University": {
    name: "Waseda University",
    IBScore: "37-39",
    tuition: "¥1,281,000",
    rank: 199,
    img: "/img/univ_logos/Waseda_university_logo.svg.png",
  },

  "Keio University": {
    name: "Keio University",
    IBScore: "≤ 34",
    tuition: "¥1,373,350",
    rank: 214,
    img: "/img/univ_logos/Keio University.png",
  },
};
const HKUniversityInfo = {
  "Chinese University of Hongkong": {
    name: "Chinese University of Hongkong",
    IBScore: "37-39",
    tuition: "HKD 145,000",
    rank: 47,
    img: "/img/univ_logos/Chinese_University_of_Hong_Kong.png",
  },
  "Hong Kong University": {
    name: "Hong Kong University",
    IBScore: "37-39",
    tuition: "HKD 145,000",
    rank: 26,
    img: "/img/univ_logos/University_of_Hong_Kong.png",
  },
  "Hong Kong University of Science and Technology": {
    name: "Hong Kong University of Science and Technology",
    IBScore: "37-39",
    tuition: "HKD 170,000",
    rank: 60,
    img: "/img/univ_logos/Hong_Kong_University_of_Science_and_Technology.png",
  },
  "Hong Kong Polytechnic University": {
    name: "Hong Kong Polytechnic University",
    IBScore: "34-36",
    tuition: "HKD160,000",
    rank: 65,
    img: "/img/univ_logos/Hong Kong Polytechnic University.png",
  },
  "City University of Hong Kong": {
    name: "City University of Hong Kong",
    IBScore: "≤ 34",
    tuition: "HKD145,000",
    rank: 70,
    img: "/img/univ_logos/City-University-of-Hong-Kong.png",
  },
  "Hong Kong Baptist University": {
    name: "Hong Kong Baptist University",
    IBScore: "≤ 34",
    tuition: "HKD 160,000",
    rank: 295,
    img: "/img/univ_logos/Hong_Kong_Baptist_University-logo-41C356C9A4-seeklogo.com.png",
  },
  "Lingnan University, Hong Kong": {
    name: "Lingnan University, Hong Kong",
    IBScore: "≤ 34",
    tuition: "HKD 145,000",
    rank: "641-650",
    img: "/img/univ_logos/Lingnan University.png",
  },
};

export const listWrap = {
  all: {
    44: [].concat.apply(
      [],
      [
        USUniversityList[44],
        UKUniversityList[44],
        SingaporeUniversityList[44],
        KoreaUniversityList[44],
        HKUniversityList[44],
        CanadaUniversityList[44],
        AustraliaUniversityList[44],
        JapanUniversityList[44],
      ]
    ),
    43: [].concat.apply(
      [],
      [
        USUniversityList[43],
        UKUniversityList[43],
        SingaporeUniversityList[43],
        KoreaUniversityList[43],
        HKUniversityList[43],
        CanadaUniversityList[43],
        AustraliaUniversityList[43],
        JapanUniversityList[43],
      ]
    ),
    40: [].concat.apply(
      [],
      [
        USUniversityList[40],
        UKUniversityList[40],
        SingaporeUniversityList[40],
        KoreaUniversityList[40],
        HKUniversityList[40],
        CanadaUniversityList[40],
        AustraliaUniversityList[40],
        JapanUniversityList[40],
      ]
    ),
    37: [].concat.apply(
      [],
      [
        USUniversityList[37],
        UKUniversityList[37],
        SingaporeUniversityList[37],
        KoreaUniversityList[37],
        HKUniversityList[37],
        CanadaUniversityList[37],
        AustraliaUniversityList[37],
        JapanUniversityList[37],
      ]
    ),
    34: [].concat.apply(
      [],
      [
        USUniversityList[34],
        UKUniversityList[34],
        SingaporeUniversityList[34],
        KoreaUniversityList[34],
        HKUniversityList[34],
        CanadaUniversityList[34],
        AustraliaUniversityList[34],
        JapanUniversityList[34],
      ]
    ),
    33: [].concat.apply(
      [],
      [
        USUniversityList[33],
        UKUniversityList[33],
        SingaporeUniversityList[33],
        KoreaUniversityList[33],
        HKUniversityList[33],
        CanadaUniversityList[33],
        AustraliaUniversityList[33],
        JapanUniversityList[33],
      ]
    ),
  },
  us: USUniversityList,
  gb: UKUniversityList,
  sg: SingaporeUniversityList,
  kr: KoreaUniversityList,
  hk: HKUniversityList,
  ca: CanadaUniversityList,
  au: AustraliaUniversityList,
  jp: JapanUniversityList,
};
export const infoWrap = {
  all: {
    ...USUniversityInfo,
    ...UKUniversityInfo,
    ...SingaporeUniversityInfo,
    ...KoreaUniversityInfo,
    ...HKUniversityInfo,
    ...CanadaUniversityInfo,
    ...AustraliaUniversityInfo,
    ...JapanUniversityInfo,
  },
  us: USUniversityInfo,
  gb: UKUniversityInfo,
  sg: SingaporeUniversityInfo,
  kr: KoreaUniversityInfo,
  hk: HKUniversityInfo,
  ca: CanadaUniversityInfo,
  au: AustraliaUniversityInfo,
  jp: JapanUniversityInfo,
};
