import "@/styles/global.css";

import Footer from "@/components/layoutComponents/Footer";
import AppLayout from "@/components/layoutComponents/AppLayout";

import Providers from "@/components/Provider";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata = {
  title: "Monthly IB",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <SessionWrapper>
        <html lang="en">
          <body>
            <AppLayout />
            <Providers>{children}</Providers>
            <footer>
              <Footer />
            </footer>
          </body>
        </html>
      </SessionWrapper>
    </>
  );
}
