import "@/styles/global.css";

import AppLayout from "@/components/layoutComponents/AppLayout";
import Footer from "@/components/layoutComponents/Footer";


export const metadata = {
  title: "Monthly IB",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="app_shell">
          <AppLayout />
          <div className="app_content">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
