
export const chapterOptions = {
  Biology: [
    "Water",
    "Nucleic acids",
    "Origins of cells",
    "Cell structure",
    "Viruses",
    "Diversity of organisms",
    "Classification & cladistics",
    "Evolution & speciation",
    "Conservation of biodiversity",
    "Carbohydrates & lipids",
    "Proteins",
    "Membranes & membrane transport",
    "Organelles & compartmentalisation",
    "Cell specialisation",
    "Gas exchange",
    "Transport",
    "Muscle & motility",
    "Adaptation to environment",
    "Ecological niches",
    "Enzymes & metabolism",
    "Cell respiration",
    "Photosynthesis",
    "Chemical signalling",
    "Neural signalling",
    "Integration of body systems",
    "Defence against disease",
    "Populations & communities",
    "Transfers of energy & matter",
    "DNA replication",
    "Protein synthesis",
    "Mutations & gene editing",
    "Cell & nuclear division",
    "Gene expression",
    "Water potential",
    "Reproduction",
    "Inheritance",
    "Homeostasis",
    "Natural selection",
    "Stability & change",
    "Climate change"
  ],
  Chemistry: [
    "Introduction to the particulate nature of matter",
    "The nuclear atom",
    "Electron configurations",
    "Counting particles by mass: the mole",
    "Ideal gases",
    "The ionic model",
    "The covalent model",
    "The metallic model",
    "From models to materials",
    "The periodic table—classification of elements",
    "Functional groups—classification of organic compounds",
    "Measuring enthalpy change",
    "Energy cycles in reactions",
    "Energy from fuels",
    "Entropy & spontaneity",
    "How much? The amount of chemical change (stoichiometry)",
    "How fast? The rate of chemical change (kinetics)",
    "How far? The extent of chemical change (equilibrium)",
    "Proton‑transfer reactions (acid–base)",
    "Electron‑transfer reactions (redox)",
    "Electron‑sharing reactions (organic)",
    "Electron‑pair‑sharing reactions (coordination / complex formation)"
  ],
  Physics: [
    "Describing motion",
    "Newton’s laws, impulse",
    "Mechanical energy, power",
    "Rotation, torque, stability",
    "Inertial frames, time dilation",
    "Specific‑heat, latent heat",
    "Energy balance, IR absorption",
    "Ideal/real gases, pressure",
    "First & second laws, engines",
    "Ohm’s law, Kirchhoff rules",
    "Oscillators, energy exchange",
    "Superposition, reflection",
    "Diffraction, interference",
    "Nodes, antinodes, Q‑factor",
    "Applications to light & sound",
    "Field strength, potential",
    "Coulomb, Biot–Savart, Gauss",
    "Charged‑particle dynamics",
    "Faraday, Lenz, AC generators",
    "Energy levels, spectra",
    "Wave–particle duality, models",
    "Half‑life, decay series",
    "Chain reactions, reactors",
    "Stellar processes, mass–energy"
  ],
  English: [
    "Novel",
    "Poem",
    "Play",
    "Article/Opinion Column/Essay",
    "Speech/Interview",
    "Advertisement",
    "Graphic Novel/Cartoon/Illustration",
    "Film/Photograph",
    "Infographic"
  ],
  Econ: [
    "What is economics?",
    "How do economists approach the world?",
    "Demand",
    "Supply",
    "Competitive market equilibrium",
    "Critique of the maximizing behaviour of consumers and producers",
    "Elasticity of demand",
    "Elasticity of supply",
    "Role of government in microeconomics",
    "Market failure—externalities and common pool or common access resources",
    "Market failure—public goods",
    "Market failure—asymmetric information",
    "Market failure—market power",
    "The market’s inability to achieve equity",
    "Measuring economic activity and illustrating its variations",
    "Variations in economic activity—aggregate demand and aggregate supply",
    "Macroeconomic objectives",
    "Economics of inequality and poverty",
    "Demand management (demand-side policies)—monetary policy",
    "Demand management—fiscal policy",
    "Supply-side policies",
    "Benefits of international trade",
    "Types of trade protection",
    "Arguments for and against trade control/protection",
    "Economic integration",
    "Exchange rates",
    "Balance of payments",
    "Sustainable development",
    "Measuring development",
    "Barriers to economic growth and/or economic development",
    "Economic growth and/or economic development strategies"
  ],
  Business: [
    "Introduction to business management",
    "Types of organizations",
    "Organizational objectives",
    "Stakeholders",
    "External environment",
    "Growth and evolution",
    "Organizational planning tools",
    "Functions and evolution of human resource management",
    "Organizational structure",
    "Leadership and management",
    "Motivation",
    "Organizational (corporate) culture",
    "Industrial/employee relations",
    "Sources of finance",
    "Costs and revenues",
    "Break-even analysis",
    "Final accounts",
    "Profitability and liquidity ratio analysis",
    "Efficiency ratio analysis",
    "Cash flow",
    "Investment appraisal",
    "Budgets",
    "The role of marketing",
    "Marketing planning",
    "Sales forecasting",
    "Market research",
    "The four Ps",
    "The extended marketing mix of seven Ps",
    "International marketing",
    "E-commerce",
    "The role of operations management",
    "Production methods",
    "Lean production and quality management",
    "Location",
    "Production planning",
    "Research and development",
    "Crisis management and contingency planning"
  ],
  Psychology: [
    "Brain and behaviour",
    "Localization",
    "Neuroplasticity",
    "Neurotransmitters and behaviour",
    "Techniques used to study the brain in relation to behaviour",
    "Hormones and pheromones and behaviour",
    "The influence of hormones on behaviour",
    "The influence of pheromones on behaviour",
    "Genetics and behaviour",
    "Genes and behaviour, genetic similarities",
    "Evolutionary explanations for behaviour",
    "The role of animal research in understanding human behaviour",
    "Cognitive processing",
    "Models of memory",
    "Schema theory",
    "Thinking and decision-making",
    "Reliability of cognitive processes",
    "Reconstructive memory",
    "Biases in thinking and decision-making",
    "Emotion and cognition",
    "The influence of emotion on cognitive processes",
    "Cognitive processing in the digital world",
    "The individual and the group",
    "Social identity theory",
    "Social cognitive theory",
    "Stereotypes",
    "Cultural origins of behaviour and cognition",
    "Culture and its influence on behaviour and cognition",
    "Cultural dimensions",
    "Cultural influences on individual attitudes, identity and behaviours",
    "Enculturation",
    "Acculturation",
    "The influence of globalization on individual behaviour",
    "Factors influencing diagnosis",
    "Normality versus abnormality",
    "Classification systems",
    "Validity and reliability of diagnosis",
    "The role of clinical biases in diagnosis",
    "Etiology of abnormal psychology",
    "Prevalence rates and disorders",
    "Explanations for disorders: Biological explanations for depression",
    "Explanations for disorders: Cognitive explanations for depression",
    "Explanations for disorders: Sociocultural explanations for depression",
    "Treatment of disorders",
    "Assessing the effectiveness of treatment",
    "Biological treatment of depression",
    "Psychological treatment of depression",
    "The role of culture in treatment",
    "Determinants of health",
    "Prevalence rates of health problems",
    "Biopsychosocial (BPS) model of health and well-being",
    "Health problems",
    "Biological explanations of health problems",
    "Psychological explanations of health problems",
    "Social explanations of health problems",
    "Risk and protective factors",
    "Health promotion",
  ]
};